version: '3.9'
services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=http://pygradus.kiedanski.com:8000
    command: node server/server.js
    ports:
      - 3000:3000
